### ISSUE TITLE
Global installation issues with symfony console v3.03

### ISSUE THREAD

**Issue by mccrodp** [4AllDigital/DockerDrupalCli#1]
On running: `composer global require dockerdrupal/cli:1.0.5` I get:

````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dockerdrupal/cli 1.0.5 requires stecman/symfony-console-completion ^0.5.1 -> satisfiable by stecman/symfony-console-completion[0.5.1].
    - Installation request for dockerdrupal/cli 1.0.5 -> satisfiable by dockerdrupal/cli[1.0.5].
    - Conclusion: remove symfony/console v3.0.3
    - Conclusion: don't install symfony/console v3.0.3
    - stecman/symfony-console-completion 0.5.1 requires symfony/console ~2.2 -> satisfiable by symfony/console[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
````

> Installation request for symfony/console (locked at v3.0.3) -> satisfiable by symfony/console[v3.0.3].

But my `~/.composer/composer.json` has only the following

````json
{
    "require": {
        "drush/drush": "^8.0"
    }
}
````

**Comment by joemewes** [comment]
hmm.  I remember I had to put ```"dockerdrupal/cli": "1.0.5"``` in my composer.json... but now I'll see if I can figure out why there's this dependency issue, so thats not required.

**Comment by joemewes** [comment]
ok. seems to be an incompatibility with drush/drush 8.0.* and my dependencies in dockerdrupal/cli

when I remove drush and all .composer/vendor/symfony/* stuff and then install dd/cli it works fine.

also remove drush via composer and running the following also seems to work :

```
composer global require dockerdrupal/cli:1.0.5
```

followed by:

```
composer global require drush/drush
```

the resultant composer.json looks like the following:

{
  "require": {
    "dockerdrupal/cli": "dev-master",
    "drush/drush": "^8.1"
  }
}


-----------
you could also just put this into your composer.json file and run ```composer global update```

do let me know what you think and/or how you get on.

**Comment by joemewes** [comment]
@mccrodp ^^^^

**Comment by mccrodp** [comment]
Installed successfully with that composer file it seems. Thanks.

**Comment by joemewes** [comment]
@mccrodp as composer dependencies issues are ongoing with updates I've added a .phar installer/launcher  to smooth the download and install process FYI

all the best
