### ISSUE TITLE
Fatal error on running `dockerdrupal env`

### ISSUE THREAD

**Issue by mccrodp** [4AllDigital/DockerDrupalCli#2]
```
dockerdrupal env my-site -t D7


 If required, please type admin password to add '127.0.0.1 docker.dev' to /etc/hosts



Notice: Undefined variable: output in /Users/paulmccrodden/.composer/vendor/dockerdrupal/cli/src/Command/InitCommand.php on line 177
Password:
Fatal error: Call to a member function writeln() on a non-object in /Users/paulmccrodden/.composer/vendor/dockerdrupal/cli/src/Command/InitCommand.php on line 178
```

**Comment by joemewes** [comment]
you have the latest version installed?

```dockerdrupal --version```

**Comment by joemewes** [comment]
be great to get some traction on this... feedback could help drive it towards integration with main DockerDrupal env... behat/selenium and also more options as to what container/composer config to include etc etc.

thanks again for the input and testing time/patience.

**Comment by mccrodp** [comment]
'dockerdrupal --version' output
>Docker Drupal version 1.0.5

I had to revert to using MAMP in the end. I got the Wordpress Quickstart working and then was able to get Drupal working, but I found that once I mounted the volume even with same settings.php, that I get:

>PDOException: SQLSTATE[HY000] [2002] No such file or directory in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).

So, this is an issue with all envs, something fishy going on with Docker for Mac, although I was working on a React project last and all was ok connecting to mysql container.

What we need it a Drupal Quickstart that mounts the drupal root dir on host to the container and doesn't throw that error. SImilar to the Wordpress one, but incl. mounting a dir. https://docs.docker.com/compose/wordpress/

If I can get it sorted over next while, I'll work towards that. If you got a chance in the meantime, feel free also, haha. Thanks for all your work, will take a look again soon.

**Comment by joemewes** [comment]
@mccrodp - I'll post a video of clean D7 running in under 4/5 mins once the containers are downloaded (which you may already have done).  

I realise its a big pain testing stuff that is in BETA and takes time you don't have./.... so much appreciated.  thanks

**Comment by mccrodp** [comment]
Sounds good. For me, the whole Docker ecosystem is still in beta once it get to the application layer, there's just not enough docs or troubleshooting out there yet for achieving a quick fix for specific use cases. It's all research, trial & error and experience.

Thanks!

**Comment by joemewes** [comment]
@mccrodp - version 1.0.7 resolves env function issue:

also - here's a video of the intended experience : https://www.youtube.com/watch?v=FoDeyEPEhiY

**Comment by joemewes** [comment]
should be fixed now.
